/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type GetKeyRequest = {
    keyId: string;
};

/** @internal */
export namespace GetKeyRequest$ {
    export type Inbound = {
        keyId: string;
    };

    export const inboundSchema: z.ZodType<GetKeyRequest, z.ZodTypeDef, Inbound> = z
        .object({
            keyId: z.string(),
        })
        .transform((v) => {
            return {
                keyId: v.keyId,
            };
        });

    export type Outbound = {
        keyId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetKeyRequest> = z
        .object({
            keyId: z.string(),
        })
        .transform((v) => {
            return {
                keyId: v.keyId,
            };
        });
}
