/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type Security = {
    rootKey?: string | undefined;
};

/** @internal */
export namespace Security$ {
    export type Inbound = {
        rootKey?: string | undefined;
    };

    export const inboundSchema: z.ZodType<Security, z.ZodTypeDef, Inbound> = z
        .object({
            rootKey: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.rootKey === undefined ? null : { rootKey: v.rootKey }),
            };
        });

    export type Outbound = {
        rootKey?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Security> = z
        .object({
            rootKey: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.rootKey === undefined ? null : { rootKey: v.rootKey }),
            };
        });
}
