// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type GetKeyRequest struct {
	KeyID string `queryParam:"style=form,explode=true,name=keyId"`
}

func (o *GetKeyRequest) GetKeyID() string {
	if o == nil {
		return ""
	}
	return o.KeyID
}

type GetKeyResponse struct {
	HTTPMeta components.HTTPMetadata
	// The configuration for a single key
	Key *components.Key
}

func (o *GetKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetKeyResponse) GetKey() *components.Key {
	if o == nil {
		return nil
	}
	return o.Key
}
