// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type VerifyKeyResponse struct {
	HTTPMeta components.HTTPMetadata
	// The verification result
	V1KeysVerifyKeyResponse *components.V1KeysVerifyKeyResponse
}

func (o *VerifyKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *VerifyKeyResponse) GetV1KeysVerifyKeyResponse() *components.V1KeysVerifyKeyResponse {
	if o == nil {
		return nil
	}
	return o.V1KeysVerifyKeyResponse
}
