workflowVersion: 1.0.0
speakeasyVersion: 1.285.4 
sources:
    unkey-spec:
        inputs:
            - location: https://api.unkey.dev/openapi.json
        registry:
            location: registry.speakeasyapi.dev/sagar-demo/sagar-demo/unkey-spec
targets:
    unkey-go:
        target: go
        source: unkey-spec
        output: ./go
    unkey-ts:
        target: typescript
        source: unkey-spec
        output: ./typescript
